site_name: "DOCUMENTACIÓN REEF"
site_description: "DOCUMENTACIÓN REEF"

repo_url: "https://bitbucket.org/map-capacitacion/trn_cap_fun"
edit_uri_template: 'src/develop/docs/{path}?mode=edit&at=develop'

plugins:
  - techdocs-core

markdown_extensions:
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - footnotes
  - attr_list
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
